[build]
command = "if [ ! -d $HOME/flutter ]; then git clone https://github.com/flutter/flutter.git -b stable --depth 1 $HOME/flutter; fi && export PATH=$PATH:$HOME/flutter/bin && flutter config --no-analytics && flutter pub get && flutter build web --release"
output = "build/web"
install_command = "echo 'Skipping unnecessary npm install' && exit 0" # ✅ NOUVELLE COMMANDE AGRESSIVE

[build.environment]
NODE_VERSION = "18"
# ...