[build]
command = "echo 'Using pre-built files from build/web'"
# Le dossier de sortie pointe maintenant vers 'web'
output = "web" 

[build.environment]
NODE_VERSION = "18"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200